name: CI/CD Pipeline
#declencheur
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
   runs-on: ubuntu-latest
  steps:
  #recuperation de code
  - name: Checkout code
    uses: actions/checkout@v3
  #connecter a dockerhub
  -name: Login to Docker Hub 
   uses: docker/login-action@v2
   with:
    username: ${{secrets.DOCKERHUB_USERNAME }}
    password: ${{secrets.DOCKERHUB_TOKEN }}
  #construire et pousser l image du backend
  -name: Build and Push Spring Boot Image
   uses: docker/build-push-actions@v4
   with:
    context: ./springboot/app 
    push: true
    tags: ${{secrets.DOCKERHUB_USERNAME }}/spring-app:latest
  #construire et pousser l image du frontend
  -name: Build and Push Angular Image
   uses: docker/build-push-actions@v4
   with:
    context: ./angular-app
    push: true
    tags: ${{secrets.DOCKERHUB_USERNAME }}/spring-app:latest
